services:
  mongodb:
    platform: ${MONGO_PLATFORM}
    image: mongo:7.0.7
    container_name: mongodb
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: python src/main.py
    stdin_open: true
    tty: true
